import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ErrorWrapper } from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<header 
    style={{backgroundColor:"blue",
      padding:"5px"
    }}>
      <p> This is my hearder</p>
    </header>
    <ErrorWrapper>
     {children}
    </ErrorWrapper>
        
        <footer style={{backgroundColor:"green"}}>
  <p>Author: Hege Refsnes<br></br>
  <a href="mailto:hege@example.com">Teebag@example.com</a></p>
</footer>
      </body>
      
    </html>
  );
}
